/**
 * Component Tests: BulkRetryDialog (Story 7-27, AC-7.27.6-9)
 *
 * Test Coverage:
 * - AC-7.27.6: Retry All Failed button visibility
 * - AC-7.27.7: Selective retry checkboxes
 * - AC-7.27.8: Bulk retry confirmation dialog with count
 * - AC-7.27.9: Retry success/failure feedback
 *
 * Note: This test file is generated by TEA automation workflow.
 * The BulkRetryDialog component needs to be created to pass these tests.
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// Mock data factories
import {
  createBulkRetryResponse,
  type BulkRetryResponse,
} from '../../../../e2e/fixtures/queue.factory';

// Placeholder component for tests to compile
// TODO: Remove this when actual component is created
interface BulkRetryDialogProps {
  open: boolean;
  onClose: () => void;
  selectedDocumentIds: string[];
  retryAll?: boolean;
  onRetrySuccess?: (response: BulkRetryResponse) => void;
  onRetryError?: (error: Error) => void;
}

const BulkRetryDialog = ({
  open,
  onClose,
  selectedDocumentIds,
  retryAll = false,
  onRetrySuccess,
  onRetryError,
}: BulkRetryDialogProps) => {
  if (!open) return null;

  const count = retryAll ? 'all failed' : selectedDocumentIds.length;
  const handleConfirm = async () => {
    // Simulated API call - actual implementation will use useMutation
    try {
      const response = createBulkRetryResponse(selectedDocumentIds.length, 0);
      onRetrySuccess?.(response);
      onClose();
    } catch (error) {
      onRetryError?.(error as Error);
    }
  };

  return (
    <div role="dialog" aria-labelledby="bulk-retry-title" data-testid="bulk-retry-dialog">
      <h2 id="bulk-retry-title">Confirm Retry</h2>
      <p data-testid="retry-count-message">
        Retry {typeof count === 'number' ? `${count} failed documents` : count}?
      </p>
      <div>
        <button onClick={onClose} data-testid="cancel-button">
          Cancel
        </button>
        <button onClick={handleConfirm} data-testid="confirm-button">
          Confirm Retry
        </button>
      </div>
    </div>
  );
};

// Wrapper with QueryClient
function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}

describe('BulkRetryDialog Component (Story 7-27)', () => {
  const user = userEvent.setup();

  describe('[P0] AC-7.27.8: Bulk retry confirmation dialog', () => {
    it('should render dialog when open is true', () => {
      render(
        <BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={['doc-1', 'doc-2']} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('bulk-retry-dialog')).toBeInTheDocument();
      expect(screen.getByRole('dialog')).toBeInTheDocument();
    });

    it('should not render dialog when open is false', () => {
      render(
        <BulkRetryDialog open={false} onClose={vi.fn()} selectedDocumentIds={['doc-1', 'doc-2']} />,
        { wrapper: createWrapper() }
      );

      expect(screen.queryByTestId('bulk-retry-dialog')).not.toBeInTheDocument();
    });

    it('should display count of selected documents in confirmation message', () => {
      render(
        <BulkRetryDialog
          open={true}
          onClose={vi.fn()}
          selectedDocumentIds={['doc-1', 'doc-2', 'doc-3']}
        />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('retry-count-message')).toHaveTextContent(
        'Retry 3 failed documents?'
      );
    });

    it('should display "all failed" when retryAll is true', () => {
      render(
        <BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={[]} retryAll={true} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('retry-count-message')).toHaveTextContent('Retry all failed');
    });

    it('should have Cancel and Confirm buttons', () => {
      render(<BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={['doc-1']} />, {
        wrapper: createWrapper(),
      });

      expect(screen.getByTestId('cancel-button')).toBeInTheDocument();
      expect(screen.getByTestId('confirm-button')).toBeInTheDocument();
    });

    it('should call onClose when Cancel is clicked', async () => {
      const onClose = vi.fn();

      render(<BulkRetryDialog open={true} onClose={onClose} selectedDocumentIds={['doc-1']} />, {
        wrapper: createWrapper(),
      });

      await user.click(screen.getByTestId('cancel-button'));

      expect(onClose).toHaveBeenCalledTimes(1);
    });
  });

  describe('[P0] AC-7.27.9: Retry success feedback', () => {
    it('should call onRetrySuccess with response when retry succeeds', async () => {
      const onRetrySuccess = vi.fn();

      render(
        <BulkRetryDialog
          open={true}
          onClose={vi.fn()}
          selectedDocumentIds={['doc-1', 'doc-2']}
          onRetrySuccess={onRetrySuccess}
        />,
        { wrapper: createWrapper() }
      );

      await user.click(screen.getByTestId('confirm-button'));

      await waitFor(() => {
        expect(onRetrySuccess).toHaveBeenCalled();
      });

      // Verify response structure
      const response = onRetrySuccess.mock.calls[0][0] as BulkRetryResponse;
      expect(response).toHaveProperty('queued');
      expect(response).toHaveProperty('failed');
      expect(response).toHaveProperty('errors');
    });

    it('should close dialog after successful retry', async () => {
      const onClose = vi.fn();

      render(
        <BulkRetryDialog
          open={true}
          onClose={onClose}
          selectedDocumentIds={['doc-1']}
          onRetrySuccess={vi.fn()}
        />,
        { wrapper: createWrapper() }
      );

      await user.click(screen.getByTestId('confirm-button'));

      await waitFor(() => {
        expect(onClose).toHaveBeenCalled();
      });
    });

    it('should include queued count in success response', async () => {
      const onRetrySuccess = vi.fn();

      render(
        <BulkRetryDialog
          open={true}
          onClose={vi.fn()}
          selectedDocumentIds={['doc-1', 'doc-2', 'doc-3']}
          onRetrySuccess={onRetrySuccess}
        />,
        { wrapper: createWrapper() }
      );

      await user.click(screen.getByTestId('confirm-button'));

      await waitFor(() => {
        expect(onRetrySuccess).toHaveBeenCalled();
        const response = onRetrySuccess.mock.calls[0][0] as BulkRetryResponse;
        expect(response.queued).toBe(3);
      });
    });
  });

  describe('[P1] Error Handling', () => {
    it('should handle single document retry', () => {
      render(<BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={['doc-1']} />, {
        wrapper: createWrapper(),
      });

      expect(screen.getByTestId('retry-count-message')).toHaveTextContent(
        'Retry 1 failed documents?'
      );
    });

    it('should handle empty selection gracefully', () => {
      render(<BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={[]} />, {
        wrapper: createWrapper(),
      });

      expect(screen.getByTestId('retry-count-message')).toHaveTextContent(
        'Retry 0 failed documents?'
      );
    });
  });

  describe('[P1] Accessibility', () => {
    it('should have proper dialog role and aria-labelledby', () => {
      render(<BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={['doc-1']} />, {
        wrapper: createWrapper(),
      });

      const dialog = screen.getByRole('dialog');
      expect(dialog).toHaveAttribute('aria-labelledby', 'bulk-retry-title');
    });

    it('should have visible title element', () => {
      render(<BulkRetryDialog open={true} onClose={vi.fn()} selectedDocumentIds={['doc-1']} />, {
        wrapper: createWrapper(),
      });

      expect(screen.getByRole('heading', { level: 2 })).toHaveTextContent('Confirm Retry');
    });
  });
});

describe('BulkRetryButton Component (Story 7-27, AC-7.27.6-7)', () => {
  // Placeholder component for button tests
  const BulkRetryButton = ({
    failedCount,
    selectedCount,
    onRetryAll,
    onRetrySelected,
    disabled = false,
  }: {
    failedCount: number;
    selectedCount: number;
    onRetryAll: () => void;
    onRetrySelected: () => void;
    disabled?: boolean;
  }) => (
    <div data-testid="bulk-retry-controls">
      {failedCount > 0 && (
        <button onClick={onRetryAll} disabled={disabled} data-testid="retry-all-button">
          Retry All Failed ({failedCount})
        </button>
      )}
      {selectedCount > 0 && (
        <button onClick={onRetrySelected} disabled={disabled} data-testid="retry-selected-button">
          Retry Selected ({selectedCount})
        </button>
      )}
    </div>
  );

  const user = userEvent.setup();

  describe('[P0] AC-7.27.6: Retry All Failed button', () => {
    it('should show Retry All Failed button when failed tasks exist', () => {
      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={0}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
        />
      );

      const button = screen.getByTestId('retry-all-button');
      expect(button).toBeInTheDocument();
      expect(button).toHaveTextContent('Retry All Failed (5)');
    });

    it('should hide Retry All Failed button when no failed tasks', () => {
      render(
        <BulkRetryButton
          failedCount={0}
          selectedCount={0}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
        />
      );

      expect(screen.queryByTestId('retry-all-button')).not.toBeInTheDocument();
    });

    it('should call onRetryAll when Retry All Failed is clicked', async () => {
      const onRetryAll = vi.fn();

      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={0}
          onRetryAll={onRetryAll}
          onRetrySelected={vi.fn()}
        />
      );

      await user.click(screen.getByTestId('retry-all-button'));

      expect(onRetryAll).toHaveBeenCalledTimes(1);
    });
  });

  describe('[P0] AC-7.27.7: Selective retry', () => {
    it('should show Retry Selected button when tasks are selected', () => {
      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={2}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
        />
      );

      const button = screen.getByTestId('retry-selected-button');
      expect(button).toBeInTheDocument();
      expect(button).toHaveTextContent('Retry Selected (2)');
    });

    it('should hide Retry Selected button when no tasks selected', () => {
      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={0}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
        />
      );

      expect(screen.queryByTestId('retry-selected-button')).not.toBeInTheDocument();
    });

    it('should call onRetrySelected when Retry Selected is clicked', async () => {
      const onRetrySelected = vi.fn();

      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={3}
          onRetryAll={vi.fn()}
          onRetrySelected={onRetrySelected}
        />
      );

      await user.click(screen.getByTestId('retry-selected-button'));

      expect(onRetrySelected).toHaveBeenCalledTimes(1);
    });

    it('should show both buttons when failed tasks exist and some are selected', () => {
      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={2}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
        />
      );

      expect(screen.getByTestId('retry-all-button')).toBeInTheDocument();
      expect(screen.getByTestId('retry-selected-button')).toBeInTheDocument();
    });
  });

  describe('[P1] Button States', () => {
    it('should disable buttons when disabled prop is true', () => {
      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={2}
          onRetryAll={vi.fn()}
          onRetrySelected={vi.fn()}
          disabled={true}
        />
      );

      expect(screen.getByTestId('retry-all-button')).toBeDisabled();
      expect(screen.getByTestId('retry-selected-button')).toBeDisabled();
    });

    it('should not call handlers when buttons are disabled', async () => {
      const onRetryAll = vi.fn();

      render(
        <BulkRetryButton
          failedCount={5}
          selectedCount={0}
          onRetryAll={onRetryAll}
          onRetrySelected={vi.fn()}
          disabled={true}
        />
      );

      await user.click(screen.getByTestId('retry-all-button'));

      expect(onRetryAll).not.toHaveBeenCalled();
    });
  });
});
