/**
 * Component Tests: FilterTabs (Story 7-27, AC-7.27.11-14)
 *
 * Test Coverage:
 * - AC-7.27.11: Filter tabs (All, Active, Pending, Failed)
 * - AC-7.27.12: Failed count badge showing "Failed (N)"
 * - AC-7.27.13: Filter updates task list immediately
 * - AC-7.27.14: Filter persistence during modal session
 *
 * Note: This test file is generated by TEA automation workflow.
 * The FilterTabs component needs to be created to pass these tests.
 */

import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, vi, beforeEach } from 'vitest';

// Mock data factories
import { createTaskListWithSteps } from '../../../../e2e/fixtures/queue.factory';

// Placeholder types
type FilterType = 'all' | 'active' | 'pending' | 'failed';

interface FilterCounts {
  all: number;
  active: number;
  pending: number;
  failed: number;
}

// Placeholder component for tests to compile
// TODO: Remove this when actual component is created
const FilterTabs = ({
  activeFilter,
  onFilterChange,
  counts,
}: {
  activeFilter: FilterType;
  onFilterChange: (filter: FilterType) => void;
  counts: FilterCounts;
}) => {
  const tabs: { key: FilterType; label: string }[] = [
    { key: 'all', label: 'All' },
    { key: 'active', label: 'Active' },
    { key: 'pending', label: 'Pending' },
    { key: 'failed', label: 'Failed' },
  ];

  return (
    <div role="tablist" data-testid="filter-tabs">
      {tabs.map(({ key, label }) => (
        <button
          key={key}
          role="tab"
          aria-selected={activeFilter === key}
          aria-controls={`${key}-panel`}
          data-testid={`tab-${key}`}
          onClick={() => onFilterChange(key)}
          className={activeFilter === key ? 'active-tab' : ''}
        >
          {label}
          {key === 'failed' && counts.failed > 0 && (
            <span data-testid="failed-count-badge" className="badge">
              ({counts.failed})
            </span>
          )}
        </button>
      ))}
    </div>
  );
};

describe('FilterTabs Component (Story 7-27)', () => {
  const user = userEvent.setup();

  const defaultCounts: FilterCounts = {
    all: 10,
    active: 5,
    pending: 2,
    failed: 3,
  };

  describe('[P0] AC-7.27.11: Filter tabs', () => {
    it('should render all four filter tabs', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      expect(screen.getByTestId('tab-all')).toBeInTheDocument();
      expect(screen.getByTestId('tab-active')).toBeInTheDocument();
      expect(screen.getByTestId('tab-pending')).toBeInTheDocument();
      expect(screen.getByTestId('tab-failed')).toBeInTheDocument();
    });

    it('should have correct text labels for each tab', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      expect(screen.getByTestId('tab-all')).toHaveTextContent('All');
      expect(screen.getByTestId('tab-active')).toHaveTextContent('Active');
      expect(screen.getByTestId('tab-pending')).toHaveTextContent('Pending');
      expect(screen.getByTestId('tab-failed')).toHaveTextContent('Failed');
    });

    it('should use tablist role for container', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      expect(screen.getByRole('tablist')).toBeInTheDocument();
    });

    it('should use tab role for each filter button', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      const tabs = screen.getAllByRole('tab');
      expect(tabs).toHaveLength(4);
    });
  });

  describe('[P0] AC-7.27.12: Failed count badge', () => {
    it('should show count badge on Failed tab when failed count > 0', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      const badge = screen.getByTestId('failed-count-badge');
      expect(badge).toBeInTheDocument();
      expect(badge).toHaveTextContent('(3)');
    });

    it('should not show count badge when failed count is 0', () => {
      render(
        <FilterTabs
          activeFilter="all"
          onFilterChange={vi.fn()}
          counts={{ ...defaultCounts, failed: 0 }}
        />
      );

      expect(screen.queryByTestId('failed-count-badge')).not.toBeInTheDocument();
    });

    it('should update badge when failed count changes', () => {
      const { rerender } = render(
        <FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />
      );

      expect(screen.getByTestId('failed-count-badge')).toHaveTextContent('(3)');

      rerender(
        <FilterTabs
          activeFilter="all"
          onFilterChange={vi.fn()}
          counts={{ ...defaultCounts, failed: 10 }}
        />
      );

      expect(screen.getByTestId('failed-count-badge')).toHaveTextContent('(10)');
    });

    it('should display badge within Failed tab button', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      const failedTab = screen.getByTestId('tab-failed');
      const badge = within(failedTab).getByTestId('failed-count-badge');
      expect(badge).toBeInTheDocument();
    });
  });

  describe('[P0] AC-7.27.13: Filter updates task list', () => {
    it('should call onFilterChange with "all" when All tab is clicked', async () => {
      const onFilterChange = vi.fn();

      render(
        <FilterTabs activeFilter="active" onFilterChange={onFilterChange} counts={defaultCounts} />
      );

      await user.click(screen.getByTestId('tab-all'));

      expect(onFilterChange).toHaveBeenCalledWith('all');
    });

    it('should call onFilterChange with "active" when Active tab is clicked', async () => {
      const onFilterChange = vi.fn();

      render(
        <FilterTabs activeFilter="all" onFilterChange={onFilterChange} counts={defaultCounts} />
      );

      await user.click(screen.getByTestId('tab-active'));

      expect(onFilterChange).toHaveBeenCalledWith('active');
    });

    it('should call onFilterChange with "pending" when Pending tab is clicked', async () => {
      const onFilterChange = vi.fn();

      render(
        <FilterTabs activeFilter="all" onFilterChange={onFilterChange} counts={defaultCounts} />
      );

      await user.click(screen.getByTestId('tab-pending'));

      expect(onFilterChange).toHaveBeenCalledWith('pending');
    });

    it('should call onFilterChange with "failed" when Failed tab is clicked', async () => {
      const onFilterChange = vi.fn();

      render(
        <FilterTabs activeFilter="all" onFilterChange={onFilterChange} counts={defaultCounts} />
      );

      await user.click(screen.getByTestId('tab-failed'));

      expect(onFilterChange).toHaveBeenCalledWith('failed');
    });

    it('should call onFilterChange immediately on click', async () => {
      const onFilterChange = vi.fn();

      render(
        <FilterTabs activeFilter="all" onFilterChange={onFilterChange} counts={defaultCounts} />
      );

      await user.click(screen.getByTestId('tab-failed'));

      // Should be called synchronously, not debounced
      expect(onFilterChange).toHaveBeenCalledTimes(1);
    });
  });

  describe('[P0] AC-7.27.14: Filter persistence during modal session', () => {
    it('should highlight active filter tab', () => {
      render(<FilterTabs activeFilter="failed" onFilterChange={vi.fn()} counts={defaultCounts} />);

      const failedTab = screen.getByTestId('tab-failed');
      expect(failedTab).toHaveClass('active-tab');
      expect(failedTab).toHaveAttribute('aria-selected', 'true');
    });

    it('should not highlight inactive tabs', () => {
      render(<FilterTabs activeFilter="failed" onFilterChange={vi.fn()} counts={defaultCounts} />);

      const allTab = screen.getByTestId('tab-all');
      expect(allTab).not.toHaveClass('active-tab');
      expect(allTab).toHaveAttribute('aria-selected', 'false');
    });

    it('should update highlighted tab when activeFilter prop changes', () => {
      const { rerender } = render(
        <FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />
      );

      expect(screen.getByTestId('tab-all')).toHaveClass('active-tab');

      rerender(
        <FilterTabs activeFilter="failed" onFilterChange={vi.fn()} counts={defaultCounts} />
      );

      expect(screen.getByTestId('tab-all')).not.toHaveClass('active-tab');
      expect(screen.getByTestId('tab-failed')).toHaveClass('active-tab');
    });

    it('should maintain selection state across rerenders', () => {
      const { rerender } = render(
        <FilterTabs activeFilter="pending" onFilterChange={vi.fn()} counts={defaultCounts} />
      );

      // Rerender with same activeFilter
      rerender(
        <FilterTabs
          activeFilter="pending"
          onFilterChange={vi.fn()}
          counts={{ ...defaultCounts, failed: 5 }}
        />
      );

      expect(screen.getByTestId('tab-pending')).toHaveClass('active-tab');
      expect(screen.getByTestId('tab-pending')).toHaveAttribute('aria-selected', 'true');
    });
  });

  describe('[P1] Accessibility', () => {
    it('should have aria-selected attribute on tabs', () => {
      render(<FilterTabs activeFilter="active" onFilterChange={vi.fn()} counts={defaultCounts} />);

      expect(screen.getByTestId('tab-active')).toHaveAttribute('aria-selected', 'true');
      expect(screen.getByTestId('tab-all')).toHaveAttribute('aria-selected', 'false');
    });

    it('should have aria-controls pointing to panel', () => {
      render(<FilterTabs activeFilter="all" onFilterChange={vi.fn()} counts={defaultCounts} />);

      expect(screen.getByTestId('tab-all')).toHaveAttribute('aria-controls', 'all-panel');
      expect(screen.getByTestId('tab-failed')).toHaveAttribute('aria-controls', 'failed-panel');
    });
  });

  describe('[P2] Edge Cases', () => {
    it('should handle all counts being zero', () => {
      render(
        <FilterTabs
          activeFilter="all"
          onFilterChange={vi.fn()}
          counts={{ all: 0, active: 0, pending: 0, failed: 0 }}
        />
      );

      // All tabs should still render
      expect(screen.getByTestId('tab-all')).toBeInTheDocument();
      expect(screen.queryByTestId('failed-count-badge')).not.toBeInTheDocument();
    });

    it('should handle very large counts', () => {
      render(
        <FilterTabs
          activeFilter="all"
          onFilterChange={vi.fn()}
          counts={{ all: 10000, active: 5000, pending: 2000, failed: 3000 }}
        />
      );

      expect(screen.getByTestId('failed-count-badge')).toHaveTextContent('(3000)');
    });
  });
});
