/**
 * Component Tests: StepStatusBadge (Story 7-27, AC-7.27.4-5)
 *
 * Test Coverage:
 * - AC-7.27.4: Color-coded status badges (done=green, in_progress=blue+spinner, pending=gray, error=red+icon)
 * - AC-7.27.5: Error tooltip showing full error message on hover
 *
 * Note: This test file is generated by TEA automation workflow.
 * The StepStatusBadge component needs to be created to pass these tests.
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, vi } from 'vitest';

// Mock data factories
import { type StepStatus } from '../../../../e2e/fixtures/queue.factory';

// Placeholder component for tests to compile
// TODO: Remove this when actual component is created
const StepStatusBadge = ({
  status,
  errorMessage,
}: {
  status: StepStatus;
  errorMessage?: string | null;
}) => {
  const colorClasses: Record<StepStatus, string> = {
    done: 'bg-green-500',
    in_progress: 'bg-blue-500',
    pending: 'bg-gray-400',
    error: 'bg-red-500',
  };

  return (
    <span
      data-testid="step-status-badge"
      className={`badge ${colorClasses[status]}`}
      title={status === 'error' && errorMessage ? errorMessage : undefined}
      aria-label={`Status: ${status}`}
    >
      {status === 'in_progress' && (
        <span data-testid="spinner" className="animate-spin" aria-hidden="true" />
      )}
      {status === 'error' && <span data-testid="error-icon" aria-hidden="true" />}
      {status}
    </span>
  );
};

describe('StepStatusBadge Component (Story 7-27)', () => {
  const user = userEvent.setup();

  describe('[P0] AC-7.27.4: Color-coded status badges', () => {
    it('should render green badge for "done" status', () => {
      render(<StepStatusBadge status="done" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveTextContent('done');
      expect(badge).toHaveClass('bg-green-500');
    });

    it('should render blue badge with spinner for "in_progress" status', () => {
      render(<StepStatusBadge status="in_progress" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveTextContent('in_progress');
      expect(badge).toHaveClass('bg-blue-500');

      // Should have spinner indicator
      expect(screen.getByTestId('spinner')).toBeInTheDocument();
    });

    it('should render gray badge for "pending" status', () => {
      render(<StepStatusBadge status="pending" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveTextContent('pending');
      expect(badge).toHaveClass('bg-gray-400');
    });

    it('should render red badge with error icon for "error" status', () => {
      render(<StepStatusBadge status="error" errorMessage="Test error" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveTextContent('error');
      expect(badge).toHaveClass('bg-red-500');

      // Should have error icon
      expect(screen.getByTestId('error-icon')).toBeInTheDocument();
    });

    it('should not show spinner for non-in_progress statuses', () => {
      const { rerender } = render(<StepStatusBadge status="done" />);
      expect(screen.queryByTestId('spinner')).not.toBeInTheDocument();

      rerender(<StepStatusBadge status="pending" />);
      expect(screen.queryByTestId('spinner')).not.toBeInTheDocument();

      rerender(<StepStatusBadge status="error" errorMessage="Error" />);
      expect(screen.queryByTestId('spinner')).not.toBeInTheDocument();
    });

    it('should not show error icon for non-error statuses', () => {
      const { rerender } = render(<StepStatusBadge status="done" />);
      expect(screen.queryByTestId('error-icon')).not.toBeInTheDocument();

      rerender(<StepStatusBadge status="in_progress" />);
      expect(screen.queryByTestId('error-icon')).not.toBeInTheDocument();

      rerender(<StepStatusBadge status="pending" />);
      expect(screen.queryByTestId('error-icon')).not.toBeInTheDocument();
    });
  });

  describe('[P0] AC-7.27.5: Error tooltip', () => {
    it('should show tooltip with error message on hover for error status', async () => {
      const errorMessage = 'Connection timeout after 30s';

      render(<StepStatusBadge status="error" errorMessage={errorMessage} />);

      const badge = screen.getByTestId('step-status-badge');

      // Hover over the badge
      await user.hover(badge);

      // Badge should have title attribute with error message
      expect(badge).toHaveAttribute('title', errorMessage);
    });

    it('should not show tooltip for non-error statuses', () => {
      const { rerender } = render(<StepStatusBadge status="done" />);
      expect(screen.getByTestId('step-status-badge')).not.toHaveAttribute('title');

      rerender(<StepStatusBadge status="in_progress" />);
      expect(screen.getByTestId('step-status-badge')).not.toHaveAttribute('title');

      rerender(<StepStatusBadge status="pending" />);
      expect(screen.getByTestId('step-status-badge')).not.toHaveAttribute('title');
    });

    it('should handle null error message gracefully', () => {
      render(<StepStatusBadge status="error" errorMessage={null} />);

      const badge = screen.getByTestId('step-status-badge');
      // Should not have title when error message is null
      expect(badge).not.toHaveAttribute('title');
    });

    it('should display full error message without truncation', async () => {
      const longErrorMessage =
        'Document parsing failed: The PDF file is corrupted or has an unsupported format. ' +
        'Please ensure the file is a valid PDF document and try uploading again.';

      render(<StepStatusBadge status="error" errorMessage={longErrorMessage} />);

      const badge = screen.getByTestId('step-status-badge');
      await user.hover(badge);

      // Full message should be in title attribute
      expect(badge).toHaveAttribute('title', longErrorMessage);
    });
  });

  describe('[P1] Accessibility', () => {
    it('should have appropriate aria-label for status', () => {
      render(<StepStatusBadge status="done" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveAttribute('aria-label', 'Status: done');
    });

    it('should hide decorative spinner from screen readers', () => {
      render(<StepStatusBadge status="in_progress" />);

      const spinner = screen.getByTestId('spinner');
      expect(spinner).toHaveAttribute('aria-hidden', 'true');
    });

    it('should hide decorative error icon from screen readers', () => {
      render(<StepStatusBadge status="error" errorMessage="Error" />);

      const errorIcon = screen.getByTestId('error-icon');
      expect(errorIcon).toHaveAttribute('aria-hidden', 'true');
    });

    it('should have distinct aria-label for each status', () => {
      const { rerender } = render(<StepStatusBadge status="done" />);
      expect(screen.getByTestId('step-status-badge')).toHaveAttribute('aria-label', 'Status: done');

      rerender(<StepStatusBadge status="in_progress" />);
      expect(screen.getByTestId('step-status-badge')).toHaveAttribute(
        'aria-label',
        'Status: in_progress'
      );

      rerender(<StepStatusBadge status="pending" />);
      expect(screen.getByTestId('step-status-badge')).toHaveAttribute(
        'aria-label',
        'Status: pending'
      );

      rerender(<StepStatusBadge status="error" errorMessage="Error" />);
      expect(screen.getByTestId('step-status-badge')).toHaveAttribute(
        'aria-label',
        'Status: error'
      );
    });
  });

  describe('[P2] Visual Styling', () => {
    it('should apply consistent badge base class', () => {
      render(<StepStatusBadge status="done" />);

      const badge = screen.getByTestId('step-status-badge');
      expect(badge).toHaveClass('badge');
    });

    it('should apply spinner animation class', () => {
      render(<StepStatusBadge status="in_progress" />);

      const spinner = screen.getByTestId('spinner');
      expect(spinner).toHaveClass('animate-spin');
    });
  });
});
