/**
 * Component Tests: TaskListModal Story 7-27 Extensions
 *
 * Test Coverage:
 * - AC-7.27.1: Expandable task rows
 * - AC-7.27.6-7: Bulk retry UI (Retry All Failed button, checkboxes)
 * - AC-7.27.11-14: Filter tabs integration
 *
 * Note: This test file is generated by TEA automation workflow.
 * These tests extend the existing task-list-modal.test.tsx for Story 7-27 features.
 */

import { render, screen, within, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// Mock the useQueueTasks hook
vi.mock('@/hooks/useQueueTasks', () => ({
  useQueueTasks: vi.fn(),
}));

// Mock useBulkRetry hook
vi.mock('@/hooks/useBulkRetry', () => ({
  useBulkRetry: vi.fn(() => ({
    mutate: vi.fn(),
    isPending: false,
    isSuccess: false,
  })),
}));

import { useQueueTasks } from '@/hooks/useQueueTasks';

// Mock data factories
import {
  createTaskListWithSteps,
  createTaskWithSteps,
  type TaskInfoWithSteps,
} from '../../../../e2e/fixtures/queue.factory';

const mockUseQueueTasks = vi.mocked(useQueueTasks);

// Wrapper with QueryClient
function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}

// TaskListModal component import placeholder
// TODO: Import actual component when created
// import { TaskListModal } from '../task-list-modal';

// Placeholder enhanced TaskListModal for tests to compile
const TaskListModalEnhanced = ({
  queueName,
  open,
  onClose,
}: {
  queueName: string;
  open: boolean;
  onClose: () => void;
}) => {
  const { data: tasks, isLoading, error } = useQueueTasks(queueName, 'PROCESSING', open);
  const [selectedIds, setSelectedIds] = React.useState<string[]>([]);
  const [activeFilter, setActiveFilter] = React.useState<'all' | 'active' | 'pending' | 'failed'>(
    'all'
  );
  const [expandedRows, setExpandedRows] = React.useState<Set<string>>(new Set());

  const tasksWithSteps = tasks as TaskInfoWithSteps[] | undefined;
  const failedCount = tasksWithSteps?.filter((t) => t.document_status === 'FAILED').length ?? 0;

  const toggleRowExpand = (taskId: string) => {
    const newSet = new Set(expandedRows);
    if (newSet.has(taskId)) {
      newSet.delete(taskId);
    } else {
      newSet.add(taskId);
    }
    setExpandedRows(newSet);
  };

  const toggleSelection = (taskId: string) => {
    setSelectedIds((prev) =>
      prev.includes(taskId) ? prev.filter((id) => id !== taskId) : [...prev, taskId]
    );
  };

  if (!open) return null;

  return (
    <div role="dialog" data-testid="task-list-modal">
      <h2>Active Tasks: {queueName}</h2>

      {/* Filter tabs (AC-7.27.11) */}
      <div role="tablist" data-testid="filter-tabs">
        {(['all', 'active', 'pending', 'failed'] as const).map((filter) => (
          <button
            key={filter}
            role="tab"
            aria-selected={activeFilter === filter}
            data-testid={`tab-${filter}`}
            onClick={() => setActiveFilter(filter)}
          >
            {filter.charAt(0).toUpperCase() + filter.slice(1)}
            {filter === 'failed' && failedCount > 0 && (
              <span data-testid="failed-count-badge">({failedCount})</span>
            )}
          </button>
        ))}
      </div>

      {/* Bulk retry controls (AC-7.27.6-7) */}
      <div data-testid="bulk-retry-controls">
        {failedCount > 0 && (
          <button data-testid="retry-all-button">Retry All Failed ({failedCount})</button>
        )}
        {selectedIds.length > 0 && (
          <button data-testid="retry-selected-button">Retry Selected ({selectedIds.length})</button>
        )}
      </div>

      {isLoading && <div>Loading tasks...</div>}
      {error && <div>Failed to load tasks</div>}

      {tasksWithSteps && tasksWithSteps.length > 0 && (
        <table>
          <thead>
            <tr>
              <th>
                <input type="checkbox" data-testid="select-all-checkbox" />
              </th>
              <th>Task ID</th>
              <th>Status</th>
              <th>Started</th>
              <th>Duration</th>
            </tr>
          </thead>
          <tbody>
            {tasksWithSteps.map((task) => (
              <React.Fragment key={task.task_id}>
                <tr
                  data-testid={`task-row-${task.task_id}`}
                  onClick={() => toggleRowExpand(task.task_id)}
                >
                  <td>
                    <input
                      type="checkbox"
                      checked={selectedIds.includes(task.task_id)}
                      onChange={() => toggleSelection(task.task_id)}
                      data-testid={`checkbox-${task.task_id}`}
                      onClick={(e) => e.stopPropagation()}
                    />
                  </td>
                  <td>{task.task_id.substring(0, 8)}...</td>
                  <td>{task.document_status}</td>
                  <td>{task.started_at}</td>
                  <td>{task.estimated_duration}ms</td>
                </tr>
                {expandedRows.has(task.task_id) && (
                  <tr data-testid={`expanded-row-${task.task_id}`}>
                    <td colSpan={5}>
                      <div data-testid="step-breakdown">
                        {task.processing_steps.map((step) => (
                          <div key={step.step} data-testid={`step-${step.step}`}>
                            {step.step}: {step.status}
                          </div>
                        ))}
                      </div>
                    </td>
                  </tr>
                )}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      )}

      <button onClick={onClose}>Close</button>
    </div>
  );
};

// Import React for the placeholder component
import React from 'react';

describe('TaskListModal Story 7-27 Extensions', () => {
  const user = userEvent.setup();

  const mockTasksWithSteps = createTaskListWithSteps({
    activeCount: 2,
    pendingCount: 1,
    failedCount: 2,
    completedCount: 1,
  });

  beforeEach(() => {
    vi.clearAllMocks();
    mockUseQueueTasks.mockReturnValue({
      data: mockTasksWithSteps,
      isLoading: false,
      error: null,
      isError: false,
      isPending: false,
      isSuccess: true,
      status: 'success',
      fetchStatus: 'idle',
      refetch: vi.fn(),
    } as unknown as ReturnType<typeof useQueueTasks>);
  });

  describe('[P0] AC-7.27.1: Expandable task rows', () => {
    it('should expand row when task row is clicked', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const taskRow = screen.getByTestId(`task-row-${mockTasksWithSteps[0].task_id}`);
      await user.click(taskRow);

      expect(
        screen.getByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`)
      ).toBeInTheDocument();
    });

    it('should collapse row when expanded row is clicked again', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const taskRow = screen.getByTestId(`task-row-${mockTasksWithSteps[0].task_id}`);

      // Expand
      await user.click(taskRow);
      expect(
        screen.getByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`)
      ).toBeInTheDocument();

      // Collapse
      await user.click(taskRow);
      expect(
        screen.queryByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`)
      ).not.toBeInTheDocument();
    });

    it('should show step breakdown when row is expanded', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const taskRow = screen.getByTestId(`task-row-${mockTasksWithSteps[0].task_id}`);
      await user.click(taskRow);

      const expandedRow = screen.getByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`);
      expect(within(expandedRow).getByTestId('step-breakdown')).toBeInTheDocument();
    });

    it('should allow multiple rows to be expanded simultaneously', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      // Expand first row
      await user.click(screen.getByTestId(`task-row-${mockTasksWithSteps[0].task_id}`));
      // Expand second row
      await user.click(screen.getByTestId(`task-row-${mockTasksWithSteps[1].task_id}`));

      expect(
        screen.getByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`)
      ).toBeInTheDocument();
      expect(
        screen.getByTestId(`expanded-row-${mockTasksWithSteps[1].task_id}`)
      ).toBeInTheDocument();
    });
  });

  describe('[P0] AC-7.27.6: Retry All Failed button', () => {
    it('should show Retry All Failed button when failed tasks exist', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('retry-all-button')).toBeInTheDocument();
      expect(screen.getByTestId('retry-all-button')).toHaveTextContent('Retry All Failed (2)');
    });

    it('should hide Retry All Failed button when no failed tasks', () => {
      mockUseQueueTasks.mockReturnValue({
        data: mockTasksWithSteps.filter((t) => t.document_status !== 'FAILED'),
        isLoading: false,
        error: null,
        isError: false,
        isPending: false,
        isSuccess: true,
        status: 'success',
        fetchStatus: 'idle',
        refetch: vi.fn(),
      } as unknown as ReturnType<typeof useQueueTasks>);

      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      expect(screen.queryByTestId('retry-all-button')).not.toBeInTheDocument();
    });
  });

  describe('[P0] AC-7.27.7: Selective retry checkboxes', () => {
    it('should render checkbox for each task row', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      mockTasksWithSteps.forEach((task) => {
        expect(screen.getByTestId(`checkbox-${task.task_id}`)).toBeInTheDocument();
      });
    });

    it('should toggle checkbox selection on click', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const checkbox = screen.getByTestId(`checkbox-${mockTasksWithSteps[0].task_id}`);
      expect(checkbox).not.toBeChecked();

      await user.click(checkbox);
      expect(checkbox).toBeChecked();

      await user.click(checkbox);
      expect(checkbox).not.toBeChecked();
    });

    it('should show Retry Selected button when tasks are selected', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      // Initially no selected button
      expect(screen.queryByTestId('retry-selected-button')).not.toBeInTheDocument();

      // Select a task
      await user.click(screen.getByTestId(`checkbox-${mockTasksWithSteps[0].task_id}`));

      // Button should appear
      expect(screen.getByTestId('retry-selected-button')).toBeInTheDocument();
      expect(screen.getByTestId('retry-selected-button')).toHaveTextContent('Retry Selected (1)');
    });

    it('should update selected count when multiple tasks are selected', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      await user.click(screen.getByTestId(`checkbox-${mockTasksWithSteps[0].task_id}`));
      await user.click(screen.getByTestId(`checkbox-${mockTasksWithSteps[1].task_id}`));

      expect(screen.getByTestId('retry-selected-button')).toHaveTextContent('Retry Selected (2)');
    });

    it('should not expand row when checkbox is clicked', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const checkbox = screen.getByTestId(`checkbox-${mockTasksWithSteps[0].task_id}`);
      await user.click(checkbox);

      // Row should not expand
      expect(
        screen.queryByTestId(`expanded-row-${mockTasksWithSteps[0].task_id}`)
      ).not.toBeInTheDocument();
    });
  });

  describe('[P0] AC-7.27.11: Filter tabs', () => {
    it('should render all four filter tabs', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('tab-all')).toBeInTheDocument();
      expect(screen.getByTestId('tab-active')).toBeInTheDocument();
      expect(screen.getByTestId('tab-pending')).toBeInTheDocument();
      expect(screen.getByTestId('tab-failed')).toBeInTheDocument();
    });

    it('should highlight All tab by default', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('tab-all')).toHaveAttribute('aria-selected', 'true');
    });
  });

  describe('[P0] AC-7.27.12: Failed count badge', () => {
    it('should show failed count badge on Failed tab', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      const badge = screen.getByTestId('failed-count-badge');
      expect(badge).toHaveTextContent('(2)');
    });
  });

  describe('[P1] AC-7.27.13: Filter updates task list', () => {
    it('should update active tab when filter is clicked', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      await user.click(screen.getByTestId('tab-failed'));

      expect(screen.getByTestId('tab-failed')).toHaveAttribute('aria-selected', 'true');
      expect(screen.getByTestId('tab-all')).toHaveAttribute('aria-selected', 'false');
    });
  });

  describe('[P2] Integration', () => {
    it('should maintain selections when expanding rows', async () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      // Select a task
      const checkbox = screen.getByTestId(`checkbox-${mockTasksWithSteps[0].task_id}`);
      await user.click(checkbox);
      expect(checkbox).toBeChecked();

      // Expand the row
      await user.click(screen.getByTestId(`task-row-${mockTasksWithSteps[0].task_id}`));

      // Selection should be maintained
      expect(checkbox).toBeChecked();
    });

    it('should render select-all checkbox in header', () => {
      render(
        <TaskListModalEnhanced queueName="document_processing" open={true} onClose={vi.fn()} />,
        { wrapper: createWrapper() }
      );

      expect(screen.getByTestId('select-all-checkbox')).toBeInTheDocument();
    });
  });
});
