"""Export service for converting drafts to DOCX, PDF, and Markdown formats."""

import re
from datetime import datetime
from io import BytesIO

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table

from app.models.draft import Draft


class ExportService:
    """Service for exporting drafts to various formats (DOCX, PDF, Markdown)."""

    def export_to_docx(self, draft: Draft) -> bytes:
        """Export draft to DOCX format with citation footnotes.

        Citation format:
        Main text: "OAuth 2.0 with PKCE¹..."
        Footnote ¹: Source: Tech Arch.pdf, Page 14, Section "Auth"
                     Excerpt: "OAuth 2.0 with Proof Key..."

        Args:
            draft: Draft model instance with content and citations

        Returns:
            DOCX file as bytes
        """
        doc = Document()

        # 1. Add title
        title = doc.add_heading(draft.title or "Generated Document", level=0)
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        # 2. Parse content and add paragraphs with citations
        content_lines = draft.content.split("\n")
        citation_map = {c["number"]: c for c in draft.citations}

        for line in content_lines:
            line = line.strip()
            if not line:
                continue

            # Handle headers
            if line.startswith("### "):
                doc.add_heading(line[4:], level=3)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            elif line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("- ") or line.startswith("* "):
                # Bullet list
                para = doc.add_paragraph(line[2:], style="List Bullet")
                self._add_footnotes_to_paragraph(para, citation_map)
            elif re.match(r"^\d+\.\s", line):
                # Numbered list
                para = doc.add_paragraph(
                    re.sub(r"^\d+\.\s", "", line), style="List Number"
                )
                self._add_footnotes_to_paragraph(para, citation_map)
            else:
                # Regular paragraph
                para = doc.add_paragraph()
                self._add_footnotes_to_paragraph_text(para, line, citation_map)

        # 3. Add metadata footer
        section = doc.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = (
            f"Generated by LumiKB on {datetime.utcnow().strftime('%Y-%m-%d')}"
        )
        footer_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        # 4. Save to bytes
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        return buffer.getvalue()

    def _add_footnotes_to_paragraph(
        self, para, citation_map: dict[int, dict]
    ) -> None:
        """Add footnotes to existing paragraph (for list items)."""
        text = para.text
        citation_pattern = r"\[(\d+)\]"
        matches = list(re.finditer(citation_pattern, text))

        if not matches:
            return

        # Clear paragraph and rebuild with footnotes
        para.clear()
        last_end = 0
        for match in matches:
            # Add text before citation
            if match.start() > last_end:
                para.add_run(text[last_end : match.start()])

            # Add footnote
            citation_num = int(match.group(1))
            citation = citation_map.get(citation_num)

            if citation:
                # Note: python-docx doesn't support add_footnote on list items
                # Fallback: Keep [n] marker in text
                para.add_run(f"[{citation_num}]")
            else:
                para.add_run(f"[{citation_num}]")

            last_end = match.end()

        # Add remaining text
        if last_end < len(text):
            para.add_run(text[last_end:])

    def _add_footnotes_to_paragraph_text(
        self, para, text: str, citation_map: dict[int, dict]
    ) -> None:
        """Add text with inline footnotes to paragraph."""
        citation_pattern = r"\[(\d+)\]"
        matches = list(re.finditer(citation_pattern, text))

        last_end = 0
        for match in matches:
            # Add text before citation
            if match.start() > last_end:
                para.add_run(text[last_end : match.start()])

            # Add footnote
            citation_num = int(match.group(1))
            citation = citation_map.get(citation_num)

            if citation:
                footnote_text = self._format_citation_footnote(citation)
                try:
                    # Add footnote (Word auto-converts to superscript)
                    para.add_footnote(footnote_text)
                except AttributeError:
                    # Fallback if footnote not supported
                    para.add_run(f"[{citation_num}]")
            else:
                para.add_run(f"[{citation_num}]")

            last_end = match.end()

        # Add remaining text
        if last_end < len(text):
            para.add_run(text[last_end:])

    def _format_citation_footnote(self, citation: dict) -> str:
        """Format citation as footnote text.

        Args:
            citation: Citation dict with keys: document_name, page_number, section_header, excerpt

        Returns:
            Formatted footnote string
        """
        parts = [f"Source: {citation['document_name']}"]

        if citation.get("page_number"):
            parts.append(f"Page {citation['page_number']}")

        if citation.get("section_header"):
            parts.append(f'Section "{citation["section_header"]}"')

        if citation.get("excerpt"):
            excerpt = citation["excerpt"]
            if len(excerpt) > 200:
                excerpt = excerpt[:200] + "..."
            parts.append(f'Excerpt: "{excerpt}"')

        return ", ".join(parts)

    def export_to_pdf(self, draft: Draft) -> bytes:
        """Export draft to PDF with citation table at end.

        Layout:
        - Title page
        - Main content with [n] superscript citations
        - Citation table on final page

        Args:
            draft: Draft model instance

        Returns:
            PDF file as bytes
        """
        buffer = BytesIO()

        # 1. Create PDF document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=1 * inch,
            rightMargin=1 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        # 2. Define styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=16,
            alignment=TA_CENTER,
            spaceAfter=30,
        )

        # 3. Build content
        story = []

        # Title
        story.append(Paragraph(draft.title or "Generated Document", title_style))
        story.append(Spacer(1, 0.2 * inch))

        # Parse markdown content
        content_lines = draft.content.split("\n")

        for line in content_lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.1 * inch))
                continue

            # Handle headers
            if line.startswith("### "):
                story.append(Paragraph(line[4:], styles["Heading3"]))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles["Heading2"]))
            elif line.startswith("# "):
                story.append(Paragraph(line[2:], styles["Heading1"]))
            else:
                # Convert [n] to superscript
                para_text = re.sub(r"\[(\d+)\]", r"<super>[\1]</super>", line)
                story.append(Paragraph(para_text, styles["BodyText"]))
                story.append(Spacer(1, 0.1 * inch))

        # 4. Add citation table
        if draft.citations:
            story.append(PageBreak())
            story.append(Paragraph("References", styles["Heading2"]))
            story.append(Spacer(1, 0.2 * inch))

            # Build citation table data
            table_data = [["#", "Source", "Details"]]
            for citation in sorted(draft.citations, key=lambda c: c["number"]):
                details = f"Page {citation.get('page_number', 'N/A')}"
                if citation.get("section_header"):
                    details += f", Section: {citation['section_header']}"
                if citation.get("excerpt"):
                    excerpt = citation["excerpt"]
                    if len(excerpt) > 150:
                        excerpt = excerpt[:150] + "..."
                    details += f'\n"{excerpt}"'

                table_data.append(
                    [f"[{citation['number']}]", citation["document_name"], details]
                )

            # Create table
            citation_table = Table(table_data, colWidths=[0.5 * inch, 2 * inch, 4 * inch])
            citation_table.setStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), "#e0e0e0"),
                    ("TEXTCOLOR", (0, 0), (-1, 0), "#000000"),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 11),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("GRID", (0, 0), (-1, -1), 0.5, "#cccccc"),
                ]
            )

            story.append(citation_table)

        # 5. Build PDF
        doc.build(story)
        buffer.seek(0)

        return buffer.getvalue()

    def export_to_markdown(self, draft: Draft) -> str:
        """Export draft to markdown with [^n] footnote syntax.

        Format:
        Main text with [^1] footnotes

        ## References
        [^1]: **Doc.pdf** (Page 14) "Excerpt..."

        Args:
            draft: Draft model instance

        Returns:
            Markdown string
        """
        content = draft.content

        # 1. Convert [n] to [^n] markdown footnote syntax
        content = re.sub(r"\[(\d+)\]", r"[^\1]", content)

        # 2. Add references section
        if draft.citations:
            references = "\n\n## References\n\n"

            for citation in sorted(draft.citations, key=lambda c: c["number"]):
                ref_text = f"[^{citation['number']}]: **{citation['document_name']}**"

                if citation.get("page_number"):
                    ref_text += f" (Page {citation['page_number']}"
                    if citation.get("section_header"):
                        ref_text += f", Section: {citation['section_header']}"
                    ref_text += ")"

                if citation.get("excerpt"):
                    # Add excerpt with line break
                    excerpt = citation["excerpt"]
                    if len(excerpt) > 200:
                        excerpt = excerpt[:200] + "..."
                    ref_text += f'  \n"{excerpt}"'

                references += ref_text + "\n\n"

            content += references

        return content
